#########################################################################################
##
##   SYMBOLIC DERIVATION — Jacobian of the LinearSingleTrack state equations
##
##   Workflow for mathematical modeling:
##     1. Re-build the model's right-hand side f(x, u, t) in SymPy, mirroring the
##        shipped `_func_dyn` line-for-line.
##     2. Let the CAS compute the state Jacobian  J = df/dx  symbolically (exact —
##        no hand calculus, so no transcription/sign mistakes).
##     3. CROSS-CHECK the symbolic result against the actual code:
##          - symbolic f   vs  LinearSingleTrack._func_dyn         (model matches code)
##          - symbolic J   vs  block.op_dyn.jac_x (num. fallback)  (Jacobian matches code)
##        at many random operating points. This is what makes the derivation trustworthy.
##     4. Emit ready-to-paste Python for an analytic `jac(x, u, t)`, generated by
##        SymPy (`pycode`) so the final code is not hand-typed either.
##
##   Run:  ../.venv/Scripts/python.exe derivations/linear_single_track_jacobian.py
##   Needs: sympy  (pip install -e ".[derivations]")
##
#########################################################################################

import sys

import numpy as np
import sympy as sp

from pathsim_vehicle.linearSingleTrack import LinearSingleTrack

# SymPy's pretty-printer emits Unicode; force UTF-8 so this runs on a cp1252 console too.
try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass


def banner(step, title):
    print(f"\n{'='*85}\nSTEP {step} - {title}\n{'='*85}")


# =======================================================================================
# STEP 1 — Symbols and physical assumptions
# =======================================================================================
banner(1, "Declare symbols (state, inputs, parameters) with physical assumptions")

# State vector x = [v_y, r, psi, X, Y]   (the quantities we differentiate w.r.t.)
v_y, r, psi, X, Y = sp.symbols("v_y r psi X Y", real=True)
state = sp.Matrix([v_y, r, psi, X, Y])

# Inputs u = [delta, v_x]   (held fixed when differentiating w.r.t. the state)
delta, v_x = sp.symbols("delta v_x", real=True)

# Parameters — names chosen IDENTICAL to the class attributes so generated code maps 1:1.
# All physically positive, which lets SymPy keep sqrt(.) and fractions in clean form.
m, I_z, l_f, l_r = sp.symbols("m I_z l_f l_r", positive=True)
C_Falpha_f, C_Falpha_r, v_x_eps = sp.symbols("C_Falpha_f C_Falpha_r v_x_eps", positive=True)

print("state x =", state.T)
print("input u = [delta, v_x]")
print("params  = m, I_z, l_f, l_r, C_Falpha_f, C_Falpha_r, v_x_eps  (all > 0)")


# =======================================================================================
# STEP 2 — Smoothed forward speed (singularity guard)
# =======================================================================================
banner(2, "Smoothed denominator v_x_safe = sqrt(v_x^2 + v_x_eps^2)")

# This is the code's sign-preserving guard against the 1/v_x singularity at standstill.
# IMPORTANT: it depends only on the INPUT v_x, not on any state variable, therefore
#            d(v_x_safe)/d(state) = 0  ->  it passes through the state-Jacobian as a
#            constant. Differentiating w.r.t. v_x is NOT part of df/dx.
v_x_safe = sp.sqrt(v_x**2 + v_x_eps**2)
print("v_x_safe =", v_x_safe)


# =======================================================================================
# STEP 3 — Linearised slip angles (small-angle: tan(alpha) ~ alpha)
# =======================================================================================
banner(3, "Slip angles alpha_f, alpha_r")

alpha_f = delta - (v_y + l_f * r) / v_x_safe
alpha_r = -(v_y - l_r * r) / v_x_safe       # rear steer = 0
print("alpha_f =", alpha_f)
print("alpha_r =", alpha_r)


# =======================================================================================
# STEP 4 — Linear tyre lateral forces
# =======================================================================================
banner(4, "Linear tyre forces F_y_f = C_f*alpha_f , F_y_r = C_r*alpha_r")

F_y_f = C_Falpha_f * alpha_f
F_y_r = C_Falpha_r * alpha_r
print("F_y_f =", F_y_f)
print("F_y_r =", F_y_r)


# =======================================================================================
# STEP 5 — State-derivative vector  f(x, u) = d/dt [v_y, r, psi, X, Y]
# =======================================================================================
banner(5, "Right-hand side f — mirrors _func_dyn exactly")

dv_y = (F_y_f + F_y_r) / m - v_x * r
dr   = (l_f * F_y_f - l_r * F_y_r) / I_z
dpsi = r
dX   = v_x * sp.cos(psi) - v_y * sp.sin(psi)
dY   = v_x * sp.sin(psi) + v_y * sp.cos(psi)

f = sp.Matrix([dv_y, dr, dpsi, dX, dY])
sp.pprint(f, use_unicode=False)


# =======================================================================================
# STEP 6 — Jacobian J = df/dx   (the CAS does the calculus)
# =======================================================================================
banner(6, "Jacobian J = df/dx  (5x5)")

J = f.jacobian(state)
J = sp.simplify(J)
sp.pprint(J, use_unicode=False)


# =======================================================================================
# STEP 7 — Per-entry listing with physical meaning
# =======================================================================================
banner(7, "Non-zero entries of J (row = d/dt of, col = w.r.t.)")

names = ["v_y", "r", "psi", "X", "Y"]
for i in range(5):
    for j in range(5):
        e = sp.nsimplify(J[i, j]) if J[i, j].is_number else J[i, j]
        if J[i, j] != 0:
            print(f"  dJ[d{names[i]:>3}/d{names[j]:<3}] = {J[i, j]}")


# =======================================================================================
# STEP 8 — CROSS-CHECK against the shipped code (this is the trust anchor)
# =======================================================================================
banner(8, "Numerical cross-check: symbolic  vs  LinearSingleTrack code")

# Lambdify symbolic f and J as fast numpy callables.
arg_syms = (v_y, r, psi, X, Y, delta, v_x,
            m, I_z, l_f, l_r, C_Falpha_f, C_Falpha_r, v_x_eps)
f_lam = sp.lambdify(arg_syms, f, "numpy")
J_lam = sp.lambdify(arg_syms, J, "numpy")

# Instantiate the real block (default parameters) and read them back out.
blk = LinearSingleTrack()
P = (blk.m, blk.I_z, blk.l_f, blk.l_r, blk.C_Falpha_f, blk.C_Falpha_r, blk.v_x_eps)

rng = np.random.default_rng(0)
max_err_f = 0.0
max_abs_J = 0.0
max_rel_J = 0.0
all_close = True
N = 300
for _ in range(N):
    # random but physically sane operating point; include low speed to exercise the guard
    xx = np.array([rng.uniform(-5, 5),        # v_y
                   rng.uniform(-1, 1),         # r
                   rng.uniform(-np.pi, np.pi), # psi
                   rng.uniform(-50, 50),       # X (must not affect J)
                   rng.uniform(-50, 50)])      # Y (must not affect J)
    uu = np.array([rng.uniform(-0.15, 0.15),  # delta
                   rng.choice([rng.uniform(0.1, 1.0), rng.uniform(3, 35)])])  # v_x

    # f:  symbolic  vs  code
    f_sym  = np.asarray(f_lam(*xx, *uu, *P), dtype=float).ravel()
    f_code = np.asarray(blk._func_dyn(xx, uu, 0.0), dtype=float)
    max_err_f = max(max_err_f, np.max(np.abs(f_sym - f_code)))

    # J:  symbolic  vs  code's numerical fallback (central differences)
    J_sym  = np.asarray(J_lam(*xx, *uu, *P), dtype=float)
    J_code = np.asarray(blk.op_dyn.jac_x(xx, uu, 0.0), dtype=float)
    abs_err = np.abs(J_sym - J_code)
    rel_err = abs_err / (np.abs(J_code) + 1e-9)
    max_abs_J = max(max_abs_J, abs_err.max())
    max_rel_J = max(max_rel_J, rel_err.max())
    all_close = all_close and np.allclose(J_sym, J_code, rtol=1e-5, atol=1e-7)

print(f"  points tested            : {N}")
print(f"  max |f_sym - f_code|     : {max_err_f:.3e}   (model matches code)")
print(f"  max |J_sym - J_code|     : {max_abs_J:.3e}   (abs, central-diff limited)")
print(f"  max rel |J_sym - J_code| : {max_rel_J:.3e}   (relative)")
print(f"  np.allclose(rtol=1e-5)   : {all_close}")
print(f"\n  RESULT: {'JACOBIAN VERIFIED against shipped code' if all_close else 'MISMATCH — investigate'}")


# =======================================================================================
# STEP 9 — Emit ready-to-paste analytic jac(x, u, t)  (SymPy-generated, not hand-typed)
# =======================================================================================
banner(9, "Generated code for an analytic Jacobian method")

# Emit paste-ready code that matches the block's own style, via EXACT SymPy
# substitutions (so the printed expressions stay machine-derived, never hand-typed):
#   - factor the repeated sqrt as `v_x_safe`     (mirrors `_func_dyn`)
#   - reference parameters as `self.<attr>`        (mirrors `_func_dyn`)
# Substitution order matters: replace the sqrt FIRST (while v_x_eps is still a bare
# symbol), which also absorbs v_x_eps; only then map the remaining params to self.*.
from sympy.printing.numpy import NumPyPrinter
_np_printer = NumPyPrinter()
def npcode(expr):
    return _np_printer.doprint(expr).replace("numpy.", "np.")

v_x_safe_sym = sp.Symbol("v_x_safe", positive=True)
self_subs = {
    m: sp.Symbol("self.m"), I_z: sp.Symbol("self.I_z"),
    l_f: sp.Symbol("self.l_f"), l_r: sp.Symbol("self.l_r"),
    C_Falpha_f: sp.Symbol("self.C_Falpha_f"), C_Falpha_r: sp.Symbol("self.C_Falpha_r"),
}
J_emit = J.subs(sp.sqrt(v_x**2 + v_x_eps**2), v_x_safe_sym).subs(self_subs)

print("    def _jac_dyn(self, x, u, t):")
print('        """Analytic state Jacobian df/dx of the linear single-track equations.')
print("")
print("        Derived symbolically and cross-checked against ``_func_dyn`` in")
print("        ``derivations/linear_single_track_jacobian.py``. Independent of the")
print("        steer input ``delta`` and of the positions ``X``, ``Y``.")
print('        """')
print("        v_y, r, psi = x[0], x[1], x[2]")
print("        v_x = u[1]")
print("        v_x_safe = np.sqrt(v_x**2 + self.v_x_eps**2)")
print("        J = np.zeros((5, 5))")
for i in range(5):
    for j in range(5):
        if J_emit[i, j] != 0:
            print(f"        J[{i}, {j}] = {npcode(J_emit[i, j])}")
print("        return J")
